w3c/vc-di-bbs

index.html

This PR updates the following
- renames proof to proofValue as per a suggestion made by @dlongley and @msporny, captured in #25
- removes `revealedIndicies` and `totalStatements` as this information is going to be embedded into the proofValue now following the proposal in #22
Fixes #25, Fixes #22

Updates to proof syntax

---

contexts/v0.1.jsonld

#30 removed these members from the specification, however these members were not removed from the JSON-LD context. Because this JSON-LD context is un-published and this signature scheme is still experimental they are safe to remove.

fix: remove un-used elements from jsonld context

---

index.html

I realized when I was looking at the examples here that the length of the G2 public key example was too short, so I've updated it to be of proper length.

fixes the Bls12381G2Key2020 example to be proper length

---

contexts/v1/index.json

Adding the vocabulary defined in:
https://w3c-ccg.github.io/ldp-bbs2020/#bls-12-381-g1-public-key
to the context.

add Bls12381G1Key2020 to context

---

index.html

https://github.com/w3c-ccg/vc-http-api/pull/144#discussion_r589730250
Rational:
If it's a security improvement, why is it optional?
If it's not a security improvement why is it present?

Make nonce a MUST

---

index.html

Both the current reference implementations use Blake2b as the digest function instead of SHAKE, so this PR is a correction, future versions of the suite may elect to use SHAKE-256

fix: update digest algorithm used by reference implementations

---

index.html

Updates the `signature` property for `BbsBlsSignature2020` to `proofValue`
Fixes #52

fix: update signature to proofValue

---

.gitignore
index.html

This PR adds two types of signature suite `BbsBlsBoundSignature2020` and  `BbsBoundSignatureProof2020`.
They only differ from `BbsBlsSignature2020` and `BbsSignatureProof2020` in that they include a commitment to a secret value from the recipient as described in https://mattrglobal.github.io/bbs-signatures-spec/#section-3.9
The resulting proof automatically includes a zk-PoK of the secret value along with all of the other signed values. This binds the signature to the recipient.
I haven't added a proof that the secret value is the same if multiple `BbsBoundSignatureProof2020` signatures are verified at the same time, but that would be possible if folks feel it is a necessary addition.

Recipient binding

---

index.html

This PR updates the data model and algorithms sections to align with the new algorithm layout for the Data Integrity specification. 
The PR specifically does not remove any text, but rather moves the legacy BBS 2020 algorithm text into an appendix (which the Editor's may decide to keep, refactor, integrate, or delete). The PR also does not attempt to make a decision regarding the bound vs. unbound BBS Signatures.
The PR provides key representations in both `publicKeyMultibase` and `JsonWebKey` format, and I expect there needs to be further discussion about that section given that each key format takes a different approach. I do not claim to know or understand the trade-offs at this point in time, so no amount of finality about the serialization format for BBS pubic keys should be assumed …

Update specification structure to align with latest Data Integrity specification

---

index.html

As described in the title, due to limited capacity and the fact that new editors @msporny and @Wind4Greg have offered to take over duties I am steping down as editor.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/pull/97.html" title="Last updated on Nov 4, 2023, 5:02 PM UTC (9d1aaaf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/97/aa19c9e...9d1aaaf.html" title="Last updated on Nov 4, 2023, 5:02 PM UTC (9d1aaaf)">Diff</a>

Removing myself (tobias) as editor

---

index.html

This PR addresses issue https://github.com/w3c/vc-di-bbs/issues/107 by furnishing additional informative text on linkage aspects of JSON-LD node ids.
***
<a href="https://pr-preview.s3.amazonaws.com/Wind4Greg/vc-di-bbs/pull/109.html" title="Last updated on Jan 8, 2024, 10:44 PM UTC (e19aa41)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/109/ed835c7...Wind4Greg:e19aa41.html" title="Last updated on Jan 8, 2024, 10:44 PM UTC (e19aa41)">Diff</a>

Add informative text on linkage via JSON-LD node ids.

---

index.html

This PR addresses issues https://github.com/w3c/vc-di-bbs/issues/113 and https://github.com/w3c/vc-di-bbs/issues/111 related to character encodings and UTF-8.
***
<a href="https://pr-preview.s3.amazonaws.com/Wind4Greg/vc-di-bbs/pull/115.html" title="Last updated on Jan 8, 2024, 10:47 PM UTC (aa513b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/115/ed835c7...Wind4Greg:aa513b9.html" title="Last updated on Jan 8, 2024, 10:47 PM UTC (aa513b9)">Diff</a>

i18n improvements 

---

index.html

This PR addresses issue https://github.com/w3c/vc-di-bbs/issues/108 to ensure that the `created` proof option is OPTIONAL. It does this by referring to the VC Data Integrity specification for all proof options and only mentioning proof options explicitly where their values are in some way restricted. This keeps this specification better align with VC Data Integrity as well as resolving the issue.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 2, 2024, 4:45 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on …

Base Proof Options on Data Integrity with Restrictions

---

index.html

This PR addresses issue https://github.com/w3c/vc-di-bbs/issues/119  "Add note that implementers can reuse createHmacIdLabelMapFunction in createShuffledIdLabelMapFunction". 
It does this by adding and informative note ;-)
***
<a href="https://pr-preview.s3.amazonaws.com/Wind4Greg/vc-di-bbs/pull/130.html" title="Last updated on Jan 19, 2024, 5:08 PM UTC (3b7dd70)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/130/ed835c7...Wind4Greg:3b7dd70.html" title="Last updated on Jan 19, 2024, 5:08 PM UTC (3b7dd70)">Diff</a>

Add informative note about code reuse

---

index.html

This PR addresses issue https://github.com/w3c/vc-di-bbs/issues/121. Where the text erroneously talks of "ECDSA-SD base proof" or "ECDSA-SD derived proof" these have been changed to "BBS".
***
<a href="https://pr-preview.s3.amazonaws.com/Wind4Greg/vc-di-bbs/pull/123.html" title="Last updated on Jan 11, 2024, 10:15 PM UTC (e973af7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/123/ed835c7...Wind4Greg:e973af7.html" title="Last updated on Jan 11, 2024, 10:15 PM UTC (e973af7)">Diff</a>

Remove copy and paste errors wrt ECDSA-SD header values.

---

index.html

This PR addresses issue https://github.com/w3c/vc-di-bbs/issues/132. It updates the outdated reference and terminology in the introduction. It also removes the outdated reference from the local bibliography.
***
<a href="https://pr-preview.s3.amazonaws.com/Wind4Greg/vc-di-bbs/pull/133.html" title="Last updated on Jan 17, 2024, 4:58 PM UTC (c02db3a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/133/ed835c7...Wind4Greg:c02db3a.html" title="Last updated on Jan 17, 2024, 4:58 PM UTC (c02db3a)">Diff</a>

Remove reference to RDF Normalization

---

index.html

This PR addresses issue https://github.com/w3c/vc-di-bbs/issues/120 regarding the number of elements involved with proof and verification processing. The names of the elements involved are correct the *informative* count of the number of those elements was not and is fixed by this PR.
***
<a href="https://pr-preview.s3.amazonaws.com/Wind4Greg/vc-di-bbs/pull/124.html" title="Last updated on Jan 19, 2024, 5:14 PM UTC (80c82a4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/124/ed835c7...Wind4Greg:80c82a4.html" title="Last updated on Jan 19, 2024, 5:14 PM UTC (80c82a4)">Diff</a>

Informative change to fix incorrect count of number of elements.

---

index.html

This PR addresses issue https://github.com/w3c/vc-di-bbs/issues/139 to bring this specification in line with the [VC-DI-ECDSA](https://w3c.github.io/vc-di-ecdsa/#base-proof-configuration-ecdsa-sd-2023) specification on the pass through of additional options during proof configuration.
***
<a href="https://pr-preview.s3.amazonaws.com/Wind4Greg/vc-di-bbs/pull/141.html" title="Last updated on Mar 3, 2024, 9:40 PM UTC (f3dc5cf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/141/cfef8e3...Wind4Greg:f3dc5cf.html" title="Last updated on Mar 3, 2024, 9:40 PM UTC (f3dc5cf)">Diff</a>

Update Proof Configuration Procedure to Pass Through Proof options

---

index.html

This PR addresses issue https://github.com/w3c/vc-di-bbs/issues/139 which references a similar issue that arose in ECDSA-SD https://github.com/w3c/vc-di-ecdsa/issues/58. This PR gives specific value for the HMAC key length and provides a reference that justifies the chosen value.
***
<a href="https://pr-preview.s3.amazonaws.com/Wind4Greg/vc-di-bbs/pull/143.html" title="Last updated on Mar 3, 2024, 9:46 PM UTC (0154d53)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/143/cfef8e3...Wind4Greg:0154d53.html" title="Last updated on Mar 3, 2024, 9:46 PM UTC (0154d53)">Diff</a>

Specify HMAC key size

---

index.html

This PR aligns the specification with the new cryptosuite interface introduced by PR w3c/vc-data-integrity#244.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/pull/144.html" title="Last updated on Mar 14, 2024, 7:51 PM UTC (892868f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/144/1917a17...892868f.html" title="Last updated on Mar 14, 2024, 7:51 PM UTC (892868f)">Diff</a>

Update algorithms to align with new cryptosuite interface

---

index.html

See title
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/pull/147.html" title="Last updated on Apr 28, 2024, 3:39 PM UTC (c034cf8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/147/a63511e...c034cf8.html" title="Last updated on Apr 28, 2024, 3:39 PM UTC (c034cf8)">Diff</a>

Use v2 context for the data-integrity

---

.github/workflows/auto-publish.yml

As the title says. 
This PR should be merged (1) ***after*** the publication of the CR on 2024-04-04 and (2) ***before*** any other PR merge.

Update auto-publish.yml for CR Drafts

---

index.html

Addresses a small typo mentioned in this issue: https://github.com/w3c/vc-di-bbs/issues/154
***
<a href="https://pr-preview.s3.amazonaws.com/aljones15/vc-di-bbs/pull/159.html" title="Last updated on Apr 18, 2024, 4:03 PM UTC (cb298e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/159/4abda10...aljones15:cb298e8.html" title="Last updated on Apr 18, 2024, 4:03 PM UTC (cb298e8)">Diff</a>

Correct small typo DataIntegrityProof not DataIntegirtyProof.

---

index.html

This is the same issue as https://github.com/w3c/vc-di-eddsa/issues/78.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/pull/169.html" title="Last updated on Jun 9, 2024, 8:42 AM UTC (cc724f3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/vc-di-bbs/169/c6a198c...cc724f3.html" title="Last updated on Jun 9, 2024, 8:42 AM UTC (cc724f3)">Diff</a>

Remove the 'Universal' from the RDFC references.
